### ISSUE TITLE
Unable to use sizeMapping without error

### ISSUE THREAD

**Issue by tmkeesey-ln** [IainMcHugh/goopubtag#17]
**Describe the bug**
The `sizeMapping` property causes an error in the debug console: `Invalid arguments: Slot.defineSizeMapping('Size mapping must be an array').`

It also does not appear to perform any responsive sizing.

**To Reproduce**

1. Use `GPTSlot` with `sizeMapping`. Example:
```jsx
import { GPTSlot, GUIDELINES } from "goopubtag";
const MyAd = () => (
        <GPTSlot
            sizes={[GUIDELINES.UNIT_SIZE.MPU_300]}
            sizeMapping={[
                {
                    viewport: [768, 50],
                    sizes: [GUIDELINES.UNIT_SIZE.MPU_300],
                },
                { viewport: GUIDELINES.UNIT_SIZE.BLANK, sizes: [] },
            ]}
            slotId="XXX"
        />
)
```
2. Use the component in a web page within a `GPTProvider` element.
3. Open the page with the Google Debugger turned on.
4. An error appears in the debug console, and the ad appears no matter what the viewport size is.

**Expected behavior**
The ad should appear only when the viewport is larger than 768x50. There should be no errors in the debug console.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version:  126.0.6478.127

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by IainMcHugh** [comment]
Thank you for raising this issue.

I have released a fix, you should be able

**Comment by tmkeesey-ln** [comment]
Thanks for the quick turnaround! Confirmed, everything's working fine on my end with `0.2.1`.
